trigger:
- dev

resources:
- repo: self

variables:
  # Set the tag to the current timestamp
  tag: "$(Build.SourceBranchName)-$(Build.BuildId)-$(Date:yyyyMMdd.HHmmss)"

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "##vso[task.setvariable variable=tag]$(Build.SourceBranchName)-$(Build.BuildId)-$(Date:yyyyMMdd.HHmmss)"
      displayName: Set image tag with timestamp
      
    # Adding logging for Docker build process
    - script: |
        echo "Building Docker image with tag: $(tag)"
        docker build -f Dockerfile -t joelwekesa/eweb:$(tag) .
      displayName: Build Docker Image
      env:
        DOCKER_BUILDKIT: 1 # Enable buildkit for better output

    # Push the Docker image to registry
    
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'
      
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'joelwekesa/eweb'
        command: 'push'
        tags: '$(tag)'

    # Check the Docker image after build
    - script: |
        echo "Docker images list:"
        docker images
      displayName: List Docker Images
