trigger:
 - dev

resources:
 - repo: self

variables:
 - group: eStoreDev
 - name: tag
   value: $(Build.BuildId)

stages:
 - stage: BuildAndPushFrontend
   displayName: Build and Push Frontend Docker Image
   jobs:
    - job: BuildAndPushFrontendImage
      displayName: Build and Push Frontend Image
      pool:
       vmImage: ubuntu-latest
      steps:
       - script: |
          echo "Building Docker image for frontend with tag: $(tag)"
          docker build -f Dockerfile -t joelwekesa/estorewebdev:$(tag) .
         displayName: Build Frontend Docker Image
         env:
          DOCKER_BUILDKIT: 1

       - task: Docker@2
         inputs:
          containerRegistry: 'docker'
          repository: 'joelwekesa/frontend'
          command: 'push'
          tags: '$(tag)'

       - script: |
          echo "Docker images list after frontend build:"
          docker images
         displayName: List Frontend Docker Images
