trigger:
- dev

resources:
- repo: self

variables:
  # Set the tag to the current timestamp
  tag: "$(Build.SourceBranchName)-$(date +%Y-%m-%d_%H%M%S)"

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    

    # Create .env
    - task: Bash@3
      displayName: Create an .env file
      inputs:
        targetType: 'inline'
        script: |
          cat <<EOT > .env
          ENVIRONMENT_NAME=production
          NEXT_GOOGLE_CLIENT_ID=$(NEXT_GOOGLE_CLIENT_ID)
          NEXT_GOOGLE_CLIENT_SECRET=$(NEXT_GOOGLE_CLIENT_SECRET)
          NEXT_PUBLIC_API_URL=$(NEXT_PUBLIC_API_URL)
          NEXT_PUBLIC_DOMAIN=$(NEXT_PUBLIC_DOMAIN)
          NEXT_PUBLIC_INVENTORY_URL=$(NEXT_PUBLIC_INVENTORY_URL)
          NEXT_PUBLIC_PER_PAGE=$(NEXT_PUBLIC_PER_PAGE)
          NEXTAUTH_SECRET=$(NEXTAUTH_SECRET)
          NEXTAUTH_URL=$(NEXTAUTH_URL)
          // put the rest of your env vars here
          EOT

    # Set image tag with timestamp
    - script: |
        echo "##vso[task.setvariable variable=tag]$(date +%Y-%m-%d_%H%M%S)"
      displayName: Set image tag with timestamp

    # Adding logging for Docker build process
    - script: |
        echo "Building Docker image with tag: $(tag)"
        docker build -f Dockerfile -t joelwekesa/eweb:$(tag) .
      displayName: Build Docker Image
      env:
        DOCKER_BUILDKIT: 1 # Enable buildkit for better output

    # Push the Docker image to registry
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'joelwekesa/eweb'
        command: 'push'
        tags: '$(tag)'

    # Check the Docker image after build
    - script: |
        echo "Docker images list:"
        docker images
      displayName: List Docker Images
