name: Docker Image CI

on:
 push:
  branches: ['dev']
 pull_request:
  branches: ['dev']

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - uses: actions/checkout@v4

   - name: Set up Docker tag with commit count and timestamp
     id: vars
     run: |
      COMMIT_COUNT=$(git rev-list --count HEAD)
      TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
      echo "TAG=${COMMIT_COUNT}-${TIMESTAMP}" >> $GITHUB_ENV

   - name: Build and Push Docker Image
     env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      NEXT_PUBLIC_PER_PAGE: ${{ secrets.NEXT_PUBLIC_PER_PAGE }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXT_GOOGLE_CLIENT_ID: ${{ secrets.NEXT_GOOGLE_CLIENT_ID }}
      NEXT_GOOGLE_CLIENT_SECRET: ${{ secrets.NEXT_GOOGLE_CLIENT_SECRET }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      NEXT_PUBLIC_INVENTORY_URL: ${{ secrets.NEXT_PUBLIC_INVENTORY_URL }}
      NEXT_PUBLIC_DOMAIN: ${{ secrets.NEXT_PUBLIC_DOMAIN }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
     run: |
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker build . --file Dockerfile --tag $DOCKER_USERNAME/eweb:${{ env.TAG }}
      docker push $DOCKER_USERNAME/eweb:${{ env.TAG }}
